/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndkbuildjni_MyJni */

#ifndef _Included_com_example_ndkbuildjni_MyJni
#define _Included_com_example_ndkbuildjni_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndkbuildjni_MyJni
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndkbuildjni_MyJni_get
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
